- name: Create user
  hosts: centos
  become: yes

  tasks:

  - name: Create groups
    group:
      name: "{{item}}"     
      state: present
    loop:
       - dev
       - test

  - name: Create users
    user:
      name: "{{item.clientname}}"
      shell: /bin/bash
      groups: dev,test
      append: yes
      home: /home/"{{item.homedir}}"
    with_items:
      - {clientname: centos1, homedir: centos1}
      - {clientname: centos2, homedir: centos2}
