---
  name: Check survey
  hosts: all
  become: yes

  vars:
    packages: 
             - telnet
             - vim

  tasks:

  - name: Yum Inst
    yum:
      pkg: "{{packages}}"
      state: present
